# Generated by Django 2.2.6 on 2019-11-13 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0003_auto_20191111_0744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='cover',
            new_name='album_cover',
        ),
    ]
